#! /bin/bash


gcc -g -std=c99 keygen.c -o keygen
gcc -g -std=c99 otp_enc.c client.c -o otp_enc
gcc -g -std=c99 otp_enc_d.c daemon.c -o otp_enc_d
gcc -g -std=c99 otp_dec.c client.c -o otp_dec
gcc -g -std=c99 otp_dec_d.c daemon.c -o otp_dec_d
